#!/bin/sh

# File needs to be called /hooks/build relative to the Dockerfile.
# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg "GIT_VERSION=`git describe --abbrev=9 --dirty --always --tags --long 2> /dev/null`" \
             -t $IMAGE_NAME .
